version: "3"

services:
  server:
    build: ./server
    image: mesh_simulator_server
    volumes:
      - ./server:/server
    ports:
      - "8887:8088"
    working_dir: /server
    command: bash -c "/mesh_simulator_server -httpaddress=0.0.0.0:8088 -historyseconds=1800"
    restart: always
